from pydantic import BaseModel, Field
from datetime import datetime, timezone
from typing import Optional

class MQTTMachineTelemetry(BaseModel):
    machine_id: str
    temperature: float
    rpm: int
    pressure: float
    vibration: float
    humidity: int
    tool_wear: float
    power: float
    noise: int
    product_count: int
    defect_count: int
    current: float | None = None
    voltage: float | None = None
    power_kw: float | None = None
    motor_load: float | None = None
    spindle_load: float | None = None
    coolant_level: float | None = None
    flow_rate: float | None = None
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))

class QualityAnalysisResult(BaseModel):
    machine_id: str
    health_score: float
    quality_score: float
    risk_level: str
    inspection_result: str
    issues: list["MonitoringIssue"] = Field(default_factory=list)
    last_updated: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))


class MonitoringIssue(BaseModel):
    """A deterministic monitoring finding; never generated by the LLM."""

    issue_type: str
    severity: str
    parameter: str
    current_value: float
    threshold: float
    description: str
